# config/services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: ../src

  App\Client\GoogleCalendarClient:
    arguments:
      $calendarUrl: '%env(GOOGLE_CALENDAR_URL)%'

  App\Client\KirbyClient:
    arguments:
      $newsDir: 'aktuelles'

  App\Client\FacebookClient:
    arguments:
      $newsDir: 'aktuelles'
      $accessToken: '%env(FACEBOOK_ACCESS_TOKEN)%'