# config/services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: ../src

  App\Client\GoogleCalendar:
    arguments:
      $calendarUrl: '%env(GOOGLE_CALENDAR_URL)%'